### PR TITLE
fix: move config to env variables

### PR DESCRIPTION
**Pull request by ahervy**
This pull request introduces the following changes to this project:

- Updated code to use environment variables (.env)
- Added `dotenv` package as a dependency to manage environment variables more effectively
- Updated README to reflect these changes

This is the first step towards creating a tutorial for our developer portal.

### CODE REVIEW

**Comment by qlikossbuild** [comment]
Hi, and thanks for contributing!

**Note:** If you are part of Qlik:
follow the process outlined on the internal developer portal instead.
Reach out to open-source@qlik.com if you do not have access to that developer portal.

---

Before we can handle your pull request we need you to sign our contributor license agreement.
This is a one-time process and enables you to contribute without hassle to any of the qlik-oss repositories in the future.

And it only takes a few minutes! Here are some useful links to get you started:

* [Sign the CLA](https://github.com/qlik-oss/open-source/blob/master/sign-cla.md#sign-the-cla)
* [Rationale behind the CLA](https://github.com/qlik-oss/open-source/blob/master/cla-rationale.md)
* [Qlik Open Source repository](https://github.com/qlik-oss/open-source#open-source-at-qlik-rd)
* [Official Slack team](https://developer.qlik.com/slack)

Having troubles? Feel free to reach out to us either here or on Slack!

**Note:** Once the CLA is sorted, you should rebase/touch this pull request to trigger an update of this CLA status.

**Comment by withdave** [comment]
I'd like to take this opportunity to add a few other improvements in - I'll raise a PR against this and we can merge them whole improvement in together

**Comment by ahervy** [comment]
> I'd like to take this opportunity to add a few other improvements in - I'll raise a PR against this and we can merge them whole improvement in together

@withdave, we had previously discussed a few other improvements, such as creating a separate OAuth client for the front-end, adding a callback page, and displaying the new embed object types.
I didn’t include these changes in this PR to avoid bundling too many updates at once. Let me know if you'd like me to add these here.

**Comment by withdave** [comment]
Added additional fixes in https://github.com/qlik-oss/qlik-cloud-embed-oauth-impersonation/pull/24, couldn't point them here due to source repo being different

**Pull request closed without merging**
